using System.Collections;
using UnityEngine;
using UnityEngine.UI;

namespace FlowForge.Core
{
    /// <summary>
    /// Lightweight scene-level controller used by the concrete prototype scene generated by
    /// FlowForgeSceneBuilder. It keeps the first scene playable even before the deeper
    /// simulation/prefab pipeline is expanded.
    /// </summary>
    public class FlowForgePrototypeSceneManager : MonoBehaviour
    {
        [Header("Scene Objects")]
        public Camera isoCamera;
        public Light directionalLight;
        public Transform[] machines;
        public Transform operatorAvatar;
        public Transform visualFeedbackAnchor;

        [Header("HUD")]
        public Text scoreLeanText;
        public Text scrapsText;
        public Text trsText;
        public Text stockText;
        public Text feedbackText;
        public Button apply5SButton;

        [Header("Prototype Metrics")]
        [Range(0, 100)] public int leanScore = 55;
        [Range(0f, 1f)] public float scrapRate = 0.18f;
        [Range(0f, 1f)] public float trs = 0.62f;
        [Min(0)] public int stock = 14;

        private bool fiveSApplied;
        private Coroutine feedbackRoutine;

        private void Awake()
        {
            ConfigureSceneDefaults();
            WireButton();
            RefreshHud();
        }

        private void OnValidate()
        {
            leanScore = Mathf.Clamp(leanScore, 0, 100);
            scrapRate = Mathf.Clamp01(scrapRate);
            trs = Mathf.Clamp01(trs);
            stock = Mathf.Max(0, stock);
        }

        public void Apply5S()
        {
            if (fiveSApplied)
            {
                return;
            }

            fiveSApplied = true;
            leanScore = Mathf.Clamp(leanScore + 18, 0, 100);
            scrapRate = Mathf.Clamp01(scrapRate * 0.55f);
            trs = Mathf.Clamp01(trs + 0.12f);
            stock = Mathf.Max(0, Mathf.RoundToInt(stock * 0.7f));

            foreach (var machine in machines)
            {
                if (machine != null)
                {
                    machine.localScale *= 0.92f;
                }
            }

            if (apply5SButton != null)
            {
                apply5SButton.interactable = false;
            }

            if (feedbackText != null)
            {
                feedbackText.text = "5S appliqué : flux clarifié, rebuts réduits, score Lean en hausse.";
            }

            if (feedbackRoutine != null)
            {
                StopCoroutine(feedbackRoutine);
            }

            feedbackRoutine = StartCoroutine(ShowVisualFeedback());
            RefreshHud();
        }

        private void ConfigureSceneDefaults()
        {
            if (isoCamera != null)
            {
                isoCamera.orthographic = true;
                isoCamera.orthographicSize = 8f;
            }

            if (directionalLight != null)
            {
                directionalLight.type = LightType.Directional;
                directionalLight.intensity = 1.15f;
            }
        }

        private void WireButton()
        {
            if (apply5SButton == null)
            {
                return;
            }

            apply5SButton.onClick.RemoveListener(Apply5S);
            apply5SButton.onClick.AddListener(Apply5S);
        }

        private void RefreshHud()
        {
            if (scoreLeanText != null)
            {
                scoreLeanText.text = $"Score Lean : {leanScore}/100";
            }

            if (scrapsText != null)
            {
                scrapsText.text = $"Rebuts : {scrapRate:P0}";
            }

            if (trsText != null)
            {
                trsText.text = $"TRS : {trs:P0}";
            }

            if (stockText != null)
            {
                stockText.text = $"Stock : {stock}";
            }
        }

        private IEnumerator ShowVisualFeedback()
        {
            var anchor = visualFeedbackAnchor != null ? visualFeedbackAnchor.position : transform.position + Vector3.up * 2f;
            for (var i = 0; i < 12; i++)
            {
                var sparkle = GameObject.CreatePrimitive(PrimitiveType.Sphere);
                sparkle.name = "5S Visual Feedback";
                sparkle.transform.position = anchor + new Vector3(Random.Range(-2.5f, 2.5f), Random.Range(0.3f, 1.6f), Random.Range(-1.2f, 1.2f));
                sparkle.transform.localScale = Vector3.one * 0.22f;

                var renderer = sparkle.GetComponent<Renderer>();
                renderer.material = new Material(Shader.Find("Standard"));
                renderer.material.color = new Color(1f, 0.82f, 0.18f);

                Destroy(sparkle, 1.2f);
                yield return new WaitForSeconds(0.04f);
            }
        }
    }
}
